import styles from '../style/page.module.css';
import {TextPage} from '@/components/pageLayout';
export default function Home() {
  return (
      <TextPage>

          <div className={styles.bodyText} style={{marginTop: "0vh",}}>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dui sapien eget mi proin sed. Arcu odio ut sem nulla pharetra diam. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Leo integer malesuada nunc vel risus commodo. A condimentum vitae sapien pellentesque. Posuere sollicitudin aliquam ultrices sagittis. Nisi est sit amet facilisis magna etiam tempor orci. Sem fringilla ut morbi tincidunt augue interdum velit euismod. Malesuada pellentesque elit eget gravida cum. Cras semper auctor neque vitae tempus. Urna molestie at elementum eu facilisis sed. Nullam eget felis eget nunc lobortis mattis. Aliquam sem et tortor consequat id porta nibh. Lorem ipsum dolor sit amet consectetur.
          </p>
          <p>
            Congue eu consequat ac felis. Sit amet massa vitae tortor condimentum lacinia quis vel eros. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Nec dui nunc mattis enim ut. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet. Eu non diam phasellus vestibulum lorem sed risus ultricies. Eu scelerisque felis imperdiet proin fermentum leo. Donec enim diam vulputate ut pharetra sit amet aliquam id. Porta non pulvinar neque laoreet suspendisse interdum. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Leo a diam sollicitudin tempor id eu nisl. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Massa ultricies mi quis hendrerit dolor magna. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Augue mauris augue neque gravida in fermentum. Est sit amet facilisis magna etiam. Massa tempor nec feugiat nisl pretium. Non pulvinar neque laoreet suspendisse interdum consectetur libero id. Quisque id diam vel quam elementum pulvinar.
          </p>
          <p>
            Venenatis urna cursus eget nunc scelerisque viverra mauris. Quam viverra orci sagittis eu volutpat odio facilisis. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Eu tincidunt tortor aliquam nulla facilisi. Ut morbi tincidunt augue interdum velit euismod in. Enim blandit volutpat maecenas volutpat blandit aliquam. Natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Varius vel pharetra vel turpis. Tincidunt tortor aliquam nulla facilisi cras fermentum odio. Erat imperdiet sed euismod nisi porta lorem mollis aliquam.
          </p>
          <p>
            Maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Et netus et malesuada fames ac turpis egestas sed tempus. Suspendisse sed nisi lacus sed viverra. Ut faucibus pulvinar elementum integer enim. In dictum non consectetur a erat nam at lectus. Ac feugiat sed lectus vestibulum mattis. Vel pharetra vel turpis nunc eget lorem dolor sed viverra. Commodo elit at imperdiet dui accumsan sit. Hendrerit dolor magna eget est. Nunc aliquet bibendum enim facilisis.
          </p>
          <p>
            Morbi non arcu risus quis varius quam quisque. Porttitor lacus luctus accumsan tortor posuere. Elementum eu facilisis sed odio morbi quis. Vitae et leo duis ut diam. Hendrerit dolor magna eget est lorem ipsum. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae. Facilisis volutpat est velit egestas dui id ornare arcu odio. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Et molestie ac feugiat sed lectus vestibulum mattis. Id volutpat lacus laoreet non curabitur gravida arcu ac. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Venenatis urna cursus eget nunc scelerisque. Urna id volutpat lacus laoreet non curabitur gravida arcu ac. Purus non enim praesent elementum facilisis leo vel. Tellus id interdum velit laoreet id donec ultrices. Amet nisl suscipit adipiscing bibendum est ultricies integer quis. Ut etiam sit amet nisl purus. Ut sem nulla pharetra diam sit amet nisl suscipit adipiscing. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Id diam vel quam elementum.
          </p>
          <p>
            Consectetur purus ut faucibus pulvinar elementum integer. Consequat id porta nibh venenatis cras sed felis eget. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci nulla. Ac placerat vestibulum lectus mauris ultrices. Duis ultricies lacus sed turpis tincidunt. Amet venenatis urna cursus eget nunc scelerisque viverra mauris in. Arcu dui vivamus arcu felis. Id porta nibh venenatis cras sed. Morbi tristique senectus et netus et malesuada. Lacinia at quis risus sed vulputate odio ut enim blandit. Cursus in hac habitasse platea dictumst. Gravida dictum fusce ut placerat. Volutpat diam ut venenatis tellus in metus vulputate eu scelerisque. Malesuada fames ac turpis egestas sed tempus urna et pharetra.
          </p>
          <p>
            Vehicula ipsum a arcu cursus. Vitae elementum curabitur vitae nunc sed. Et malesuada fames ac turpis egestas. Ultrices gravida dictum fusce ut placerat orci nulla. Cursus in hac habitasse platea dictumst. Mauris rhoncus aenean vel elit. Dui accumsan sit amet nulla facilisi morbi tempus iaculis urna. Quam elementum pulvinar etiam non quam lacus. Aliquam nulla facilisi cras fermentum odio eu feugiat. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Quis auctor elit sed vulputate mi. Habitant morbi tristique senectus et. Phasellus vestibulum lorem sed risus. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla. Sit amet justo donec enim diam vulputate ut pharetra.
          </p>
          <p>
            Feugiat vivamus at augue eget. Sagittis orci a scelerisque purus semper eget duis at tellus. Vestibulum morbi blandit cursus risus at. Placerat duis ultricies lacus sed. Metus vulputate eu scelerisque felis imperdiet proin fermentum. Mauris a diam maecenas sed enim ut sem viverra aliquet. Eget magna fermentum iaculis eu. Et leo duis ut diam. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant.
          </p>
          <p>
            In dictum non consectetur a erat nam. Nulla aliquet enim tortor at auctor urna nunc. Posuere morbi leo urna molestie at elementum eu facilisis. Vel orci porta non pulvinar neque. Sagittis nisl rhoncus mattis rhoncus urna neque viverra. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Id faucibus nisl tincidunt eget nullam non. Mauris vitae ultricies leo integer malesuada nunc. Consequat semper viverra nam libero justo. Arcu non odio euismod lacinia at quis risus sed. Sed egestas egestas fringilla phasellus faucibus scelerisque. Sed odio morbi quis commodo odio. Netus et malesuada fames ac turpis egestas maecenas pharetra. Id aliquet risus feugiat in. Urna id volutpat lacus laoreet non. Eu tincidunt tortor aliquam nulla facilisi.
          </p>
          <p>
            Sit amet massa vitae tortor condimentum. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Tempus urna et pharetra pharetra massa massa ultricies. Bibendum ut tristique et egestas quis ipsum suspendisse. Nisi scelerisque eu ultrices vitae auctor. Lobortis scelerisque fermentum dui faucibus. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Est lorem ipsum dolor sit amet. Gravida arcu ac tortor dignissim convallis aenean et tortor at. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Nulla malesuada pellentesque elit eget gravida cum sociis natoque. Vulputate eu scelerisque felis imperdiet proin fermentum. Condimentum id venenatis a condimentum vitae. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. At volutpat diam ut venenatis tellus. Et ultrices neque ornare aenean euismod elementum nisi. Mi proin sed libero enim sed faucibus turpis. Cursus sit amet dictum sit amet justo.
          </p>
          <p>
            Curabitur gravida arcu ac tortor dignissim convallis aenean et. Ut eu sem integer vitae justo eget. Pellentesque sit amet porttitor eget dolor morbi non. Nascetur ridiculus mus mauris vitae ultricies leo. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Dolor purus non enim praesent elementum. Scelerisque in dictum non consectetur a erat nam at. Arcu cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Sed risus pretium quam vulputate. Diam quis enim lobortis scelerisque fermentum dui. Quis ipsum suspendisse ultrices gravida dictum fusce. Dignissim convallis aenean et tortor at risus viverra adipiscing at. Nec feugiat in fermentum posuere urna. Venenatis lectus magna fringilla urna porttitor rhoncus. Convallis posuere morbi leo urna.
          </p>
          </div>
      </TextPage>

  )
}
